<a href="https://colab.research.google.com/github/Maypulido/colab/blob/main/Analitica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
from google.colab import files
uploaded = files.upload()

KeyboardInterrupt: ignored

In [ ]:
oct18 = pd.read_excel('EEFF.xlsx',sheet_name='OCT 2018', usecols= 'A,B,E')
oct19 = pd.read_excel('EEFF.xlsx', sheet_name= 'OCT 2019',skiprows=1, usecols= 'A,C,G')
dic18 = pd.read_excel('EEFF.xlsx', sheet_name= 'DIC 2018', usecols= 'B,C,F')

In [ ]:
lista_columnas = list(oct19.columns)
lista_columnas[2] = "Saldo Final"
oct19.columns = lista_columnas

In [ ]:
oct18["Cuenta"] = oct18["Cuenta"].astype(str)
oct18["Saldo Final"] = oct18["Saldo Final"].astype(float)

oct19["Cuenta"] = oct19["Cuenta"].astype(str)
oct19["Saldo Final"] = oct19["Saldo Final"].astype(float)

dic18["Saldo Final"] = dic18["Saldo Final"].astype(float)

.str.slice(start=0, stop=4)

In [ ]:
oct18.head(5)

       Cuenta                          descripción   Saldo Final
0           1                               ACTIVO  1.309100e+08
1          11  EFECTIVO Y EQUIVALENTES AL EFECTIVO  1.580417e+06
2        1105                                 CAJA  1.073849e+05
3      110505                         CAJA GENERAL  1.056849e+05
4  1105050501                   CAJA EFECTIVO COTA  7.724977e+04

In [ ]:
oct19 = oct19.dropna()
oct19['Cuenta']=pd.to_numeric(oct19['Cuenta'])
oct19["Cuenta"] = oct19["Cuenta"].astype(int).astype(str)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [ ]:
oct19

         Cuenta                          Descripción   Saldo Final
0             1                               ACTIVO  1.983762e+08
1            11  EFECTIVO Y EQUIVALENTES AL EFECTIVO  1.897987e+06
2          1105                                 CAJA  9.541741e+04
3        110505                         CAJA GENERAL  9.371741e+04
4    1105050501                   CAJA EFECTIVO COTA  1.686681e+04
..          ...                                  ...           ...
908  6135950101        RECARGAS CLARO TIEMPO AL AIRE  4.600000e+01
909  6135950102              EXTENSIONES DE GARANTIA  8.756588e+05
910  6135950200             APLICACIONES Y SERVICIOS  5.785329e+05
911  6135950300              SERVICIOS PROFESIONALES  4.976760e+04
912  6135950400              SOLUCIONES CORPORATIVAS  8.643567e+05

[913 rows x 3 columns]

In [ ]:
oct19.head(5)

       Cuenta                          Descripción   Saldo Final
0           1                               ACTIVO  1.983762e+08
1          11  EFECTIVO Y EQUIVALENTES AL EFECTIVO  1.897987e+06
2        1105                                 CAJA  9.541741e+04
3      110505                         CAJA GENERAL  9.371741e+04
4  1105050501                   CAJA EFECTIVO COTA  1.686681e+04

In [ ]:
dic18=dic18[dic18['Saldo Final'].notna()]
dic18['Cuenta']=pd.to_numeric(dic18['Cuenta'])
dic18["Cuenta"] = dic18["Cuenta"].astype(int).astype(str)

In [ ]:
dic18

    Cuenta                    Descripción   Saldo Final
0     1105             CAJA EFECTIVO COTA  3.505073e+04
1     1105          CAJA EFECTIVO UNILAGO  2.826623e+04
2     1105           CAJA DE CHEQUES COTA  2.010600e+05
3     1105            CAJA PAGOS EN CANJE  1.176860e+02
4     1105                CAJA MENOR COTA  1.500000e+03
..     ...                            ...           ...
439   6135  RECARGAS CLARO TIEMPO AL AIRE  4.140000e+02
440   6135       APLICACIONES Y SERVICIOS  5.837013e+05
441   6135        SERVICIOS PROFESIONALES  2.994952e+04
442   6135        SOLUCIONES CORPORATIVAS  8.387577e+04
443     61                            NaN  3.026391e+08

[444 rows x 3 columns]

In [ ]:
dic18_tmp=dic18.groupby(['Cuenta']).sum()

In [ ]:
dic18_tmp.reset_index(inplace=True)

In [ ]:
dic18_tmp

    Cuenta   Saldo Final
0       11  1.848261e+06
1     1105  2.661946e+05
2     1110  1.489734e+06
3     1120  7.318712e+04
4     1125  1.914546e+04
..     ...           ...
103     54  9.199300e+04
104   5405  0.000000e+00
105   5420  9.199300e+04
106     61  3.026391e+08
107   6135  3.026391e+08

[108 rows x 2 columns]

In [ ]:
oct18=oct18[oct18['Cuenta'].str.len()==4]

In [ ]:
oct18.reset_index(inplace=True)

In [ ]:
oct18.drop('index',axis=1,inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4913: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [ ]:
oct18

   Cuenta                           descripción   Saldo Final
0    1105                                  CAJA  1.073849e+05
1    1110                                BANCOS  1.445734e+06
2    1120                     CUENTAS DE AHORRO -1.105300e+01
3    1125                                FONDOS  2.730894e+04
4    1305                              CLIENTES  4.805702e+07
..    ...                                   ...           ...
82   5315                GASTOS EXTRAORDINARIOS  7.715374e+05
83   5395                        DIVERSOS OTROS  2.392116e+05
84   5405   IMPUESTO DE RENTA Y COMPLEMENTARIOS  0.000000e+00
85   5405  COMERCIO AL POR MAYOR Y AL POR MENOR  0.000000e+00
86   6135  COMERCIO AL POR MAYOR Y AL POR MENOR  2.409812e+08

[87 rows x 3 columns]

In [ ]:
oct19=oct19[oct19['Cuenta'].str.len()==4]
oct19.reset_index(inplace=True)
oct19.drop('index',axis=1,inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4913: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [ ]:
oct19

   Cuenta                           Descripción   Saldo Final
0    1105                                  CAJA  9.541741e+04
1    1110                                BANCOS  1.685083e+06
2    1120                     CUENTAS DE AHORRO  2.364988e+04
3    1125                                FONDOS  9.383680e+04
4    1305                              CLIENTES  8.357217e+07
..    ...                                   ...           ...
82   5315                GASTOS EXTRAORDINARIOS  1.029121e+06
83   5395                        DIVERSOS OTROS  4.046842e+05
84   5405   IMPUESTO DE RENTA Y COMPLEMENTARIOS  0.000000e+00
85   5405  COMERCIO AL POR MAYOR Y AL POR MENOR  0.000000e+00
86   6135  COMERCIO AL POR MAYOR Y AL POR MENOR  3.685183e+08

[87 rows x 3 columns]

In [ ]:
dfa_temp=oct19.join(oct18.set_index('Cuenta'), on='Cuenta',lsuffix='_oct19', rsuffix='oct18')

In [ ]:
dfa_temp=dfa_temp.drop(columns='descripción')

In [ ]:
dfa=dfa_temp.join(dic18_tmp.set_index('Cuenta'), on='Cuenta')

In [ ]:
dfa

,Cuenta,Descripción,Saldo Final_oct19,Saldo Finaloct18,Saldo Final
0,1105,CAJA,9.541741e+04,1.073849e+05,2.661946e+05
1,1110,BANCOS,1.685083e+06,1.445734e+06,1.489734e+06
2,1120,CUENTAS DE AHORRO,2.364988e+04,-1.105300e+01,7.318712e+04
3,1125,FONDOS,9.383680e+04,2.730894e+04,1.914546e+04
4,1305,CLIENTES,8.357217e+07,4.805702e+07,5.345206e+07
...,...,...,...,...,...
84,5405,IMPUESTO DE RENTA Y COMPLEMENTARIOS,0.000000e+00,0.000000e+00,0.000000e+00
84,5405,IMPUESTO DE RENTA Y COMPLEMENTARIOS,0.000000e+00,0.000000e+00,0.000000e+00
85,5405,COMERCIO AL POR MAYOR Y AL POR MENOR,0.000000e+00,0.000000e+00,0.000000e+00
85,5405,COMERCIO AL POR MAYOR Y AL POR MENOR,0.000000e+00,0.000000e+00,0.000000e+00
86,6135,COMERCIO AL POR MAYOR Y AL POR MENOR,3.685183e+08,2.409812e+08,3.026391e+08

In [ ]:
lista_columnas = list(dfa.columns)
lista_columnas[4] = "Saldo Finaldic18"
dfa.columns = lista_columnas

In [ ]:
dfa['Cuenta'] = dfa['Cuenta'].astype(int)

In [ ]:
dff = dfa[dfa['Cuenta'] < 4135]

In [ ]:
dfc = dff.drop(['Saldo Finaloct18'], axis=1)

In [ ]:
esf= dfc.fillna(0)

In [ ]:
esf.sum(axis=0)

Cuenta                                                          101207
Descripción          CAJABANCOSCUENTAS DE AHORROFONDOSCLIENTESDETER...
Saldo Final_oct19                                          6307455.171
Saldo Finaldic18                                           2478090.594
dtype: object

In [ ]:
esf

,Cuenta,Descripción,Saldo Final_oct19,Saldo Finaldic18
0,1105,CAJA,9.541741e+04,2.661946e+05
1,1110,BANCOS,1.685083e+06,1.489734e+06
2,1120,CUENTAS DE AHORRO,2.364988e+04,7.318712e+04
3,1125,FONDOS,9.383680e+04,1.914546e+04
4,1305,CLIENTES,8.357217e+07,5.345206e+07
5,1399,DETERIORO CARTERA CLIENTES,-1.547971e+05,-1.239793e+05
6,1390,DEUDAS DE DIFICIL COBRO,4.658030e+04,4.658030e+04
7,1365,OTRAS CUENTAS POR COBRAR,5.748948e+04,2.066336e+04
8,1380,DEUDORES VARIOS,9.728406e+06,3.918550e+06
9,1355,ANTICIPO DE IMPUESTOS Y CONTRIBUCIONES O SALD,1.246891e+07,1.014615e+07
10,1330,PAGOS ANTICIPADOS,6.857501e+05,3.196111e+05
11,1295,OTRAS INVERSIONES,8.147840e+05,7.190040e+05
12,1435,INVENTARIOS,7.458556e+07,4.229846e+07
13,1465,INVENTARIOS EN TRANSITO,8.989436e+06,6.245462e+06
14,1499,DETERIORO DE INVENTARIOS,-4.204358e+05,-2.988249e+05
15,1520,MAQUINARIA Y EQUIPO,2.044846e+05,2.044846e+05
16,1524,EQUIPO DE OFICINA,1.134611e+06,1.118313e+06
17,1528,EQUIPO DE COMPUTACION Y COMUNICACION,2.000132e+06,1.905477e+06
18,1540,FLOTA Y EQUIPO DE TRANSPORTE,1.210044e+06,1.210044e+06
19,1592,DEPRECIACION ACUMULADA,-3.146838e+06,-2.919534e+06
20,1625,DERECHOS,4.482771e+06,7.000853e+05
21,1635,LICENCIAS,4.208678e+04,5.199965e+04
22,1710,CARGOS DIFERIDOS,1.770920e+05,0.000000e+00
23,2105,PASIVOS FINANCIEROS MD A COSTO AMORTIZADO,-5.451609e+07,-4.250877e+07
24,2115,ENTIDADES FINANCIERAS,-1.950803e+04,-7.599059e+04
25,2205,PROVEEDORES,-4.218963e+07,-2.115513e+07
26,2210,PROVEEDORES DEL EXTERIOR,-5.520869e+07,-2.546292e+07
27,2299,DIFERENCIA EN CAMBIO PROVEEDORES,4.126573e+05,-6.622734e+05
28,2335,COSTOS Y GASTOS POR PAGAR,-2.552895e+06,-1.074012e+06
29,2360,DIVIDENDOS O PARTICIPACIONES POR PAGAR,-1.879310e+05,-1.598364e+06
30,2370,RETENCIONES Y APORTES DE NÓMINA,-2.012893e+05,0.000000e+00
31,2380,ACREEDORES VARIOS,-1.958430e+05,0.000000e+00
32,2365,RETENCIONES POR PAGAR,-1.727585e+06,-1.998395e+06
33,2367,IMPUESTO A LAS VENTAS RETENIDO,-2.148321e+05,0.000000e+00
34,2368,IMPUESTO DE INDUSTRIA Y COMERCIO RETENIDO,-1.851387e+04,-1.823652e+04
35,2605,PARA COSTOS Y GASTOS,-5.524566e+06,3.330000e+03
36,2610,PARA OBLIGACIONES LABORALES,-1.272156e+06,0.000000e+00
37,2408,IMPUESTO SOBRE LAS VENTAS POR PAGAR,-3.072771e+05,-1.866955e+06
38,2412,DE INDUSTRIA Y COMERCIO,-1.628429e+06,-1.350262e+06
39,2456,A LAS IMPORTACIONES,-4.132671e+06,-1.452884e+06
40,2505,SALARIOS POR PAGAR,8.539673e+03,0.000000e+00
41,2510,LEY 50 DE 1990 Y NORMAS POSTERIORES,0.000000e+00,-5.682608e+05
42,2515,INTERESES SOBRE CESANTIAS,0.000000e+00,-6.452763e+04
43,2525,VACACIONES CONSOLIDADAS,-6.782659e+04,-4.105921e+05
44,2705,INGRESOS RECIBIDOS PARA TERCEROS,-2.271205e+06,-1.849628e+05
45,2805,ANTICIPOS Y AVANCES RECIBIDOS,-1.489195e+06,-4.800276e+05
46,3105,CAPITAL SUSCRITO Y PAGADO,-4.530000e+06,-4.530000e+06
47,3205,"PRIMA EN COLOCACIÓN DE ACCIONES, CUOTAS O PAR",-1.470000e+06,-1.470000e+06
48,3305,RESERVAS OBLIGATORIAS,-2.265000e+06,-2.129306e+06
49,3705,UTILIDADES ACUMULADAS,-1.049884e+07,-9.326241e+06

In [ ]:
esf['Saldo Final_oct19'] = esf['Saldo Final_oct19'].astype(float)
esf['Saldo Finaldic18'] = esf['Saldo Finaldic18'].astype(float)

In [ ]:
esf['Anlisis Horizontal'] = esf['Saldo Final_oct19']-esf['Saldo Finaldic18']

In [ ]:
esf

,Cuenta,Descripción,Saldo Final_oct19,Saldo Finaldic18,Anlisis Horizontal
0,1105,CAJA,9.541741e+04,2.661946e+05,-1.707772e+05
1,1110,BANCOS,1.685083e+06,1.489734e+06,1.953488e+05
2,1120,CUENTAS DE AHORRO,2.364988e+04,7.318712e+04,-4.953724e+04
3,1125,FONDOS,9.383680e+04,1.914546e+04,7.469134e+04
4,1305,CLIENTES,8.357217e+07,5.345206e+07,3.012011e+07
5,1399,DETERIORO CARTERA CLIENTES,-1.547971e+05,-1.239793e+05,-3.081784e+04
6,1390,DEUDAS DE DIFICIL COBRO,4.658030e+04,4.658030e+04,0.000000e+00
7,1365,OTRAS CUENTAS POR COBRAR,5.748948e+04,2.066336e+04,3.682612e+04
8,1380,DEUDORES VARIOS,9.728406e+06,3.918550e+06,5.809856e+06
9,1355,ANTICIPO DE IMPUESTOS Y CONTRIBUCIONES O SALD,1.246891e+07,1.014615e+07,2.322762e+06
10,1330,PAGOS ANTICIPADOS,6.857501e+05,3.196111e+05,3.661390e+05
11,1295,OTRAS INVERSIONES,8.147840e+05,7.190040e+05,9.578000e+04
12,1435,INVENTARIOS,7.458556e+07,4.229846e+07,3.228711e+07
13,1465,INVENTARIOS EN TRANSITO,8.989436e+06,6.245462e+06,2.743975e+06
14,1499,DETERIORO DE INVENTARIOS,-4.204358e+05,-2.988249e+05,-1.216109e+05
15,1520,MAQUINARIA Y EQUIPO,2.044846e+05,2.044846e+05,0.000000e+00
16,1524,EQUIPO DE OFICINA,1.134611e+06,1.118313e+06,1.629800e+04
17,1528,EQUIPO DE COMPUTACION Y COMUNICACION,2.000132e+06,1.905477e+06,9.465453e+04
18,1540,FLOTA Y EQUIPO DE TRANSPORTE,1.210044e+06,1.210044e+06,0.000000e+00
19,1592,DEPRECIACION ACUMULADA,-3.146838e+06,-2.919534e+06,-2.273042e+05
20,1625,DERECHOS,4.482771e+06,7.000853e+05,3.782686e+06
21,1635,LICENCIAS,4.208678e+04,5.199965e+04,-9.912872e+03
22,1710,CARGOS DIFERIDOS,1.770920e+05,0.000000e+00,1.770920e+05
23,2105,PASIVOS FINANCIEROS MD A COSTO AMORTIZADO,-5.451609e+07,-4.250877e+07,-1.200733e+07
24,2115,ENTIDADES FINANCIERAS,-1.950803e+04,-7.599059e+04,5.648256e+04
25,2205,PROVEEDORES,-4.218963e+07,-2.115513e+07,-2.103450e+07
26,2210,PROVEEDORES DEL EXTERIOR,-5.520869e+07,-2.546292e+07,-2.974577e+07
27,2299,DIFERENCIA EN CAMBIO PROVEEDORES,4.126573e+05,-6.622734e+05,1.074931e+06
28,2335,COSTOS Y GASTOS POR PAGAR,-2.552895e+06,-1.074012e+06,-1.478883e+06
29,2360,DIVIDENDOS O PARTICIPACIONES POR PAGAR,-1.879310e+05,-1.598364e+06,1.410433e+06
30,2370,RETENCIONES Y APORTES DE NÓMINA,-2.012893e+05,0.000000e+00,-2.012893e+05
31,2380,ACREEDORES VARIOS,-1.958430e+05,0.000000e+00,-1.958430e+05
32,2365,RETENCIONES POR PAGAR,-1.727585e+06,-1.998395e+06,2.708096e+05
33,2367,IMPUESTO A LAS VENTAS RETENIDO,-2.148321e+05,0.000000e+00,-2.148321e+05
34,2368,IMPUESTO DE INDUSTRIA Y COMERCIO RETENIDO,-1.851387e+04,-1.823652e+04,-2.773540e+02
35,2605,PARA COSTOS Y GASTOS,-5.524566e+06,3.330000e+03,-5.527896e+06
36,2610,PARA OBLIGACIONES LABORALES,-1.272156e+06,0.000000e+00,-1.272156e+06
37,2408,IMPUESTO SOBRE LAS VENTAS POR PAGAR,-3.072771e+05,-1.866955e+06,1.559678e+06
38,2412,DE INDUSTRIA Y COMERCIO,-1.628429e+06,-1.350262e+06,-2.781664e+05
39,2456,A LAS IMPORTACIONES,-4.132671e+06,-1.452884e+06,-2.679787e+06
40,2505,SALARIOS POR PAGAR,8.539673e+03,0.000000e+00,8.539673e+03
41,2510,LEY 50 DE 1990 Y NORMAS POSTERIORES,0.000000e+00,-5.682608e+05,5.682608e+05
42,2515,INTERESES SOBRE CESANTIAS,0.000000e+00,-6.452763e+04,6.452763e+04
43,2525,VACACIONES CONSOLIDADAS,-6.782659e+04,-4.105921e+05,3.427655e+05
44,2705,INGRESOS RECIBIDOS PARA TERCEROS,-2.271205e+06,-1.849628e+05,-2.086242e+06
45,2805,ANTICIPOS Y AVANCES RECIBIDOS,-1.489195e+06,-4.800276e+05,-1.009167e+06
46,3105,CAPITAL SUSCRITO Y PAGADO,-4.530000e+06,-4.530000e+06,0.000000e+00
47,3205,"PRIMA EN COLOCACIÓN DE ACCIONES, CUOTAS O PAR",-1.470000e+06,-1.470000e+06,0.000000e+00
48,3305,RESERVAS OBLIGATORIAS,-2.265000e+06,-2.129306e+06,-1.356940e+05
49,3705,UTILIDADES ACUMULADAS,-1.049884e+07,-9.326241e+06,-1.172597e+06

In [ ]:
dfr = dfa[dfa['Cuenta'] > 3705]

In [ ]:
dft = dfr.drop(['Saldo Finaldic18'], axis=1)

In [ ]:
er= dft.fillna(0)

In [ ]:
er['Anlisis Horizontal'] = er['Saldo Final_oct19']-er['Saldo Finaloct18']

In [ ]:
er['porcentaje'] = er['Anlisis Horizontal']/er['Saldo Finaloct18']

In [ ]:
er

,Cuenta,Descripción,Saldo Final_oct19,Saldo Finaloct18,Anlisis Horizontal,porcentaje
50,4135,INGRESOS POR COMERCIALIZACION,-4.098444e+08,-2.701394e+08,-1.397050e+08,0.517159
51,4175,DEVOLUCIONES EN VENTAS (DB),1.185901e+07,6.942536e+06,4.916475e+06,0.708167
52,4210,INGRESOS FINANCIEROS,-7.142561e+06,-5.484845e+06,-1.657716e+06,0.302236
53,4235,INGRESOS POR SERVICIOS,-8.161275e+06,-3.718392e+06,-4.442883e+06,1.194840
54,4240,OTROS INGRESOS,-1.638010e+04,-1.558931e+04,-7.907930e+02,0.050727
55,4250,RECUPERACIONES,-1.349364e+05,-1.193514e+05,-1.558492e+04,0.130580
56,4255,INDEMNIZACIONES,-1.585404e+05,-3.882149e+04,-1.197189e+05,3.083830
57,4295,DIVERSOS,-5.591707e+03,-1.424815e+04,8.656443e+03,-0.607549
58,5105,OPERACIONALES DE ADMINISTRACION,4.870927e+06,4.562091e+06,3.088361e+05,0.067696
59,5110,HONORARIOS,9.160157e+05,1.041386e+06,-1.253708e+05,-0.120388
60,5115,IMPUESTOS,2.398359e+05,1.904345e+05,4.940143e+04,0.259414
61,5120,ARRENDAMIENTOS,1.318274e+06,1.252860e+06,6.541358e+04,0.052211
62,5125,CONTRIBUCIONES,1.563804e+04,1.228275e+04,3.355287e+03,0.273171
63,5130,SEGUROS,1.005236e+05,1.015690e+05,-1.045343e+03,-0.010292
64,5135,SERVICIOS,8.641056e+05,7.397851e+05,1.243205e+05,0.168049
65,5140,GASTOS LEGALES,4.748100e+03,6.988625e+03,-2.240525e+03,-0.320596
66,5145,MANTENIMIENTO Y REPARACIONES,9.275224e+04,7.936091e+04,1.339133e+04,0.168740
67,5150,ADECUACIÓN E INSTALACIÓN,1.687862e+04,0.000000e+00,1.687862e+04,inf
68,5155,GASTOS DE VIAJE,1.260968e+05,1.040202e+05,2.207660e+04,0.212234
69,5160,DEPRECIACIONES,2.883621e+05,2.708608e+05,1.750131e+04,0.064614
70,5165,AMORTIZACIONES,1.833804e+05,1.895013e+05,-6.120883e+03,-0.032300
71,5195,DIVERSOS,3.678504e+05,2.449212e+05,1.229292e+05,0.501913
72,5199,PROVISIONES,1.524287e+05,2.448948e+05,-9.246607e+04,-0.377575
73,5205,GASTOS DE PERSONAL,8.495588e+06,6.942289e+06,1.553299e+06,0.223744
74,5215,IMPUESTOS,1.971505e+06,1.263801e+06,7.077039e+05,0.559980
75,5220,ARRENDAMIENTOS,2.696468e+05,2.539525e+05,1.569428e+04,0.061800
76,5235,SERVICIOS,6.977510e+06,5.291094e+06,1.686416e+06,0.318727
77,5245,MANTENIMIENTO Y REPARACIONES,7.625909e+04,4.942391e+04,2.683518e+04,0.542959
78,5255,GASTOS DE VIAJE,1.530330e+05,8.137838e+04,7.165466e+04,0.880512
79,5295,DIVERSOS,4.363829e+05,3.492163e+05,8.716666e+04,0.249607
80,5305,FINANCIEROS,9.310566e+06,1.046388e+07,-1.153313e+06,-0.110219
81,5310,PERDIDA EN VENTA Y RETIRO DE BIENES,9.686150e+04,0.000000e+00,9.686150e+04,inf
82,5315,GASTOS EXTRAORDINARIOS,1.029121e+06,7.715374e+05,2.575837e+05,0.333858
83,5395,DIVERSOS OTROS,4.046842e+05,2.392116e+05,1.654726e+05,0.691742
84,5405,IMPUESTO DE RENTA Y COMPLEMENTARIOS,0.000000e+00,0.000000e+00,0.000000e+00,NaN
84,5405,IMPUESTO DE RENTA Y COMPLEMENTARIOS,0.000000e+00,0.000000e+00,0.000000e+00,NaN
85,5405,COMERCIO AL POR MAYOR Y AL POR MENOR,0.000000e+00,0.000000e+00,0.000000e+00,NaN
85,5405,COMERCIO AL POR MAYOR Y AL POR MENOR,0.000000e+00,0.000000e+00,0.000000e+00,NaN
86,6135,COMERCIO AL POR MAYOR Y AL POR MENOR,3.685183e+08,2.409812e+08,1.275371e+08,0.529241